plugins {
    alias(libs.plugins.android.application)
    id("jacoco") //Enable the JaCoCo Plugin
}

android {
    namespace = "com.example.studybuddyapp"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "com.example.studybuddyapp"
        minSdk = 28
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {

        debug {
            enableUnitTestCoverage = true //Enable Test Coverage for Debug Builds
            enableAndroidTestCoverage = true   // For instrumented tests
        }

        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
}

dependencies {
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.activity)
    implementation(libs.constraintlayout)

    // Agora Video SDK
    implementation("io.agora.rtc:full-sdk:4.5.0")

    // Retrofit + Gson for backend API
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-scalars:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.google.code.gson:gson:2.11.0")

    testImplementation(libs.junit)
    testImplementation("org.robolectric:robolectric:4.14.1")
    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("org.mockito:mockito-inline:5.2.0")
    testImplementation("androidx.test:core:1.5.0")
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}

jacoco {
    toolVersion =  "0.8.14" //Defines which JaCoCo version will be used
}

// Create a custom JaCoCo report task
tasks.register<JacocoReport>("jacocoTestReport") {
    group = "Code coverage"
    description = "Generates reports using JaCoCo."

    // Run BOTH test types before generating report
    dependsOn("testDebugUnitTest")
     dependsOn("connectedDebugAndroidTest")
    //Configure output formats
    reports {
        xml.required.set(true) // XML -> required for SonarQube
        html.required.set(true) //HTML -> visual coverage report
    }

    // Exclude auto-generated or irrelevant files from coverage
    val fileFilter = listOf(
        "**/R.class", // Android resources classes
        "**/R$*.class", // Nested resources classes
        "**/BuildConfig.*", // Auto-generated BuildConfig
        "**/Manifest*.*", // Manifest-generated files
        "**/*Test*.*", // Exclude test classes
        "android/**/*.*" //Android framework classes
    )

    //Kotlin compiled classes for debug build
    val kotlinClasses = fileTree(layout.buildDirectory.dir("tmp/kotlin-classes/debug")) {
        exclude(fileFilter)
    }

    //Java compiled classes for debug build
    val javaClasses = fileTree(layout.buildDirectory.dir("intermediates/javac/debug")) {
        exclude(fileFilter)
    }

    // Compiled Kotlin + Java class directories
    classDirectories.setFrom(files(kotlinClasses, javaClasses))

    // Tell JacoCo where your actual source code lives
    sourceDirectories.setFrom(files("src/main/java", "src/main/kotlin"))

    //Point to the JaCoCo execution data generated by unit tests and instrumented tests
    executionData.setFrom(fileTree(layout.buildDirectory) {

        include(
            // Unit test coverage
            "outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec",

            // Instrumented test coverage
            "outputs/code_coverage/debugAndroidTest/connected/**/*.ec"
        )
    }
    )
}
